# Generated by Django 2.1.5 on 2019-08-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='added_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
